name: Docker build version 5.3

on:
  push:
    branches: [ master ]
    paths:
      - '5.3/**'
      - '.github/workflows/docker-publish-5.3.yml'
  workflow_dispatch:
    
jobs:

  buildx:
    name: Build and push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Build nuster 5.3 alpine
      run: | 
        docker build 5.3/alpine -f 5.3/alpine/Dockerfile \
        --platform linux/amd64,linux/arm64 \
        --tag ${{ secrets.DOCKERHUB_USERNAME }}/nuster:5.3-alpine \
        --push

    - name: Build nuster 5.3 debian
      run: | 
        docker build 5.3/debian -f 5.3/debian/Dockerfile \
        --platform linux/amd64,linux/arm64 \
        --tag ${{ secrets.DOCKERHUB_USERNAME }}/nuster:5.3 \
        --tag ${{ secrets.DOCKERHUB_USERNAME }}/nuster:5.3-debian \
        --push


    - name: Build nuster 5.3 ubuntu
      run: | 
        docker build 5.3/ubuntu -f 5.3/ubuntu/Dockerfile \
        --platform linux/amd64,linux/arm64 \
        --tag ${{ secrets.DOCKERHUB_USERNAME }}/nuster:5.3-ubuntu \
        --push
      
